version: "1.0"

services:
  eport-backend:
    build:
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: root
      DB_PASSWORD: "root"
      DB_NAME: rta-backend
volumes:
  postgres-data: